### ISSUE TITLE
[Bug]:  Crash: `AttributeError: module 'torch.cuda' has no attribute '_get_device_properties'. Did you mean: 'get_device_properties'?`

### ISSUE THREAD

**Issue by Torathion** [lshqqytiger/stable-diffusion-webui-directml#623]
### Checklist

- [x] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I'm struggling to use the web ui with my RX 9070 with ROCm 6.2 and Zluda. After deleting my `venv` and reinstalling everything by using `webui-user.bat` (and then executing again due to the already known clean install error), I get this error:

```bash
ONNX failed to initialize: module 'optimum.onnxruntime.modeling_diffusion' has no attribute 'ORTPipelinePart'
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\launch.py", line 48, in <module>
    main()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\launch.py", line 44, in main
    start()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\launch_utils.py", line 714, in start
    import webui
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\shared_init.py", line 75, in initialize
    from modules.rocm_triton_windows import apply_triton_patches
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\rocm_triton_windows.py", line 51, in <module>
    __get_device_properties = torch.cuda._get_device_properties # pylint: disable=protected-access
AttributeError: module 'torch.cuda' has no attribute '_get_device_properties'. Did you mean: 'get_device_properties'?
````

Here is my `webui-user.bat`

```sh
@echo off

set HIP_VISIBLE_DEVICES="0,1"
set PYTHON=C:\Users\Torathion\AppData\Local\Programs\Python\Python310\python.exe
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=

call webui.bat --use-zluda
```

### Steps to reproduce the problem

I have no idea how this even happens in the first place. I'm just executing the file and it fails to startup.

### What should have happened?

No crash

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

(I don't even reach the webui)

Windows 11 x64
Python 3.10.11
AMD RX 9070

### Console logs

```Shell
Here is the full log:


venv "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.10.1
Commit hash: <none>
ROCm: no agent was found
ROCm: version=6.2
ZLUDA support: experimental
ZLUDA load: path='C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\.zluda' nightly=False
W0801 19:07:07.114000 14628 venv\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda
Warning: caught exception 'No CUDA GPUs are available', memory monitor disabled
C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\torch\onnx\_internal\registration.py:159: OnnxExporterWarning: Symbolic function 'aten::scaled_dot_product_attention' already registered for opset 14. Replacing the existing function with new function. This is unexpected. Please report it on https://github.com/pytorch/pytorch/issues.
  warnings.warn(
ONNX failed to initialize: module 'optimum.onnxruntime.modeling_diffusion' has no attribute 'ORTPipelinePart'
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\launch.py", line 48, in <module>
    main()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\launch.py", line 44, in main
    start()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\launch_utils.py", line 714, in start
    import webui
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\shared_init.py", line 75, in initialize
    from modules.rocm_triton_windows import apply_triton_patches
  File "C:\AI\stable-diffusion-webui-amdgpu-master\stable-diffusion-webui-amdgpu-master\modules\rocm_triton_windows.py", line 51, in <module>
    __get_device_properties = torch.cuda._get_device_properties # pylint: disable=protected-access
AttributeError: module 'torch.cuda' has no attribute '_get_device_properties'. Did you mean: 'get_device_properties'?
```

**Comment by CS1o** [comment]
remove --no-half and add --skip-python-version-check to the webui-user.bat
Then make sure you have downloaded and added the gfx1201 files correctly to the rocm library like describe in the Guide at Zluda Setup Step 5.
Because the issue you got is: `ROCm: no agent was found`

**Comment by Torathion** [comment]
Sorry, for the delay.

I deleted the `.venv` , let it compile for 2 hours just to be sure (there was never a "compilation finished" message or so) and it seems to work now. I can create AI art now, despite ROCm saying there is no agent. The images look sometime very weird. Could the missing agent affect the quality of the images?

**Comment by CS1o** [comment]
Hey, good that it works now.
The image quality isnt affected by anything other than the checkpoint (model) and the settings (resolution etc) used.
For example sdxl/illustrious are trained on 1024x1024 resolution.
So 512x512 will give bad results.
